# Generated by Django 6.0.2 on 2026-07-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('email', models.CharField(default='No email found', max_length=255)),
                ('phone', models.CharField(default='No phone found', max_length=50)),
                ('skills', models.TextField(blank=True, default='')),
                ('experience_years', models.FloatField(default=0.0)),
                ('resume_text', models.TextField(blank=True, default='')),
                ('match_score', models.IntegerField(default=0)),
                ('fit_assessment', models.CharField(default='Poor Match', max_length=50)),
                ('impressive_summary', models.TextField(blank=True, default='')),
                ('requirements_needed', models.TextField(blank=True, default='')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='screener.candidate')),
            ],
        ),
    ]
