# Generated by Django 6.0.2 on 2026-07-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_collegeaccount_recruiteraccount_studentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_fake_limit', models.IntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='fake_upload_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
