# Generated by Django 6.0.7 on 2026-07-17 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_placementconfig_studentaccount_fake_upload_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('reasons', models.TextField()),
                ('resume_text', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='screener.studentaccount')),
            ],
        ),
    ]
