# Generated by Django 6.0.7 on 2026-07-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_reportedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='authenticity_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='candidate',
            name='communication_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='candidate',
            name='explainability_negative',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='explainability_positive',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fraud_score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='learning_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='candidate',
            name='quality_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='candidate',
            name='stress_test_scores',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tech_depth_score',
            field=models.IntegerField(default=80),
        ),
    ]
